### ISSUE TITLE
Modal not working within Mobirise when name starts with a number

### ISSUE THREAD

**Issue by Stage4000** [witsec/mobirise-modal-window#1]
The modal plugin appears to work fine but the "how to use" and "preview" buttons aren't working which means I have to publish to see changes within modals.

Mobirise 4.11.6

**Comment by Stage4000** [comment]
Update:
it appears that using a number as the first character breaks it just a heads up.

**Comment by witsec** [comment]
Hi @Stage4000, you're right. Inside Mobirise you can't preview the modal window. Outside Mobirise, so when published, all works fine. The "preview" button also doesn't work if the name starts with a number.

I'll have a look when I can. Thanks for reporting this.

**Comment by Stage4000** [comment]
I don't know what language mobirise uses but starting a string with a number is a no no in most languages.

**Comment by Stage4000** [comment]
Hey, it would also be cool if you added coloring options to the modals.
