### ISSUE TITLE
Pop-up appearing with default weird font instead of site's font

### ISSUE THREAD

**Issue by realrodri** [witsec/mobirise-modal-window#2]
Had to fix it adding at the end of the .html file:

```
<style>
.no-aim{
font-family: arial;
}

.modal-title{
font-family: arial;
}

.modal-body{
font-family: arial;
}
</style>
```

Before:

<img width="497" alt="Captura de pantalla 2022-07-12 a las 21 45 02" src="https://user-images.githubusercontent.com/40494400/178580859-8b730926-b355-4eed-ba27-e7ab0942816a.png">

After:

<img width="494" alt="Captura de pantalla 2022-07-12 a las 21 45 44" src="https://user-images.githubusercontent.com/40494400/178580982-175985a4-27ac-4b5e-9ab2-f138c19ff6b8.png">

You can't edit the widget tho. You need DeltaPi Settings to place them at the EOF.

**Comment by witsec** [comment]
Thanks for your message, I'll take a look when I can.

**Comment by witsec** [comment]
This should be fixed in version 4, which has just been released. It'll use the default "text" font settings as defined inside Mobirise.

**Comment by realrodri** [comment]
Lit.
